### ISSUE TITLE
Mapper: how to define object serialization/mapping code in a separate package? 

### ISSUE THREAD

**Issue by alboko** [dwhjames/aws-wrap#33]
I'm trying to separate object model case classes and their DynamoDb serialization-mapping code by having them in different packages (to provide different persistence mechanism in future). For instance, I'd like to have my `case class ApiAccessToken` in `package model` and corresponding mapping code in `object DdbApiAccessToken` in `package model.dynamodb`. 

I defined all attributes along with an implicit object for toAttributeMap/fromAttributeMap methods in DdbApiAccessToken. It compiles fine, but when I try to use mapper.loadByKey, the compiler complains that it can't find a magnet:
```
Error:(49, 54) type mismatch;
 found   : String
 required: mapper.LoadByKeyMagnet[model.ApiAccessToken]
      data <- mapper.loadByKey[ApiAccessToken](dummy.token)
                                                     ^
```

Is it possible? Am I missing something completely?

Thanks,

**Comment by dwhjames** [comment]
Hi @alboko, my first guess would be that it’s an issue of implicit scope.

The error message is unfortunately not very helpful to you (a major downside of the magnet pattern), but I suspect it can’t resolve the overloading in the magnet pattern because it can’t find the right implicit:

https://github.com/dwhjames/aws-wrap/blob/087cbdf48909b1584c42b043a5ab9b2b3e846379/src/main/scala/dynamodb/mapper.scala#L478-L498

If the necessary implicits are all in `model.dynamodb.DdbApiAccessToken`, I assume you have an

```scala
import model.dynamodb.DdbApiAccessToken._
```

or similar?

And also

```scala
import com.github.dwhjames.awswrap.dynamodb._
```

?

**Comment by alboko** [comment]
Hi Daniel,

Thanks for the answer. Yes, it’s definitely about the implicit scope. I made sure to import "DdbApiAccessToken._”. Didn’t help. Everything works if I move it to the same package.

Anyway, I ended up refactoring model classes to pure traits, introducing correspond Dbb… case classes in “model.dynamodb” package (extended from model traits) and moving mapping/serialization into their companion objects. Seems to work. And it’s probably cleaner as well.

Thanks again for the nice library.
Alex

**Comment by dwhjames** [comment]
Hi Alex,

I recently removed the use of view bound syntax (deprecated)
https://github.com/dwhjames/aws-wrap/commit/53eb5522415c208f371fcfeb0ff7aa853dd479db
I assumed that would be of no consequence.

If you did have your implicits in scope, then maybe it was an issue with finding the implicit views to `AttributeValue`.
https://github.com/dwhjames/aws-wrap/blob/master/src/main/scala/dynamodb/package.scala

In any case, I’m glad you got it to work. Debugging implicits is _not_ fun!


Dan

**Comment by alboko** [comment]
Dan,
> I recently removed the use of view bound syntax (deprecated)
> 
> 53eb552 <https://github.com/dwhjames/aws-wrap/commit/53eb5522415c208f371fcfeb0ff7aa853dd479db>
> I assumed that would be of no consequence.
> 
Thanks, I’ll keep it in mind
> If you did have your implicits in scope, then maybe it was an issue with finding the implicit views to AttributeValue.
> https://github.com/dwhjames/aws-wrap/blob/master/src/main/scala/dynamodb/package.scala <https://github.com/dwhjames/aws-wrap/blob/master/src/main/scala/dynamodb/package.scala>Right, that’s was probably the issue. I was not able to figure it out.

One more question regarding AttributeValue - is there an implicit conversion to/for Options? I ended up with quite ugly code like:
case class DdbApiCredentials(
    accountId: Long,
    accountTypeCode: String, // Enumeration.name
    accountName: Option[String],
    accountStatusCode: String,  // Enumeration.name
    clientSecret: String,
    clientPassword: String,
    accessTokenId: Option[String]
  ) extends ApiCredentials
object DdbApiCredentials {
  override def toAttributeMap(item: DdbApiCredentials): Map[String, AttributeValue] = {
    val amap = scala.collection.mutable.HashMap[String, AttributeValue](
      Attributes.accountId          -> item.accountId,
      Attributes.accountTypeCode    -> item.accountTypeCode,
      Attributes.accountStatusCode  -> item.accountStatusCode,
      Attributes.clientSecret       -> item.clientSecret,
      Attributes.clientPassword     -> item.clientPassword
    )
    // optional fields
    item.accountName foreach (v => amap += (Attributes.accountName -> v))
    item.accessTokenId foreach (v => amap += (Attributes.accessTokenId -> v))

    amap.toMap  // back to immutable
  }

  override def fromAttributeMap(amap: collection.mutable.Map[String, AttributeValue]) = new DdbApiCredentials(
    accountId         = amap(Attributes.accountId),
    accountTypeCode   = amap(Attributes.accountTypeCode),
    accountName       = amap.get(Attributes.accountName).map(_.getS),
    accountStatusCode = amap(Attributes.accountStatusCode),
    clientSecret      = amap(Attributes.clientSecret),
    clientPassword    = amap(Attributes.clientPassword),
    accessTokenId     = amap.get(Attributes.accessTokenId).map(_.getS)
  )
}
I suspect I’ll have to add my own implicit conversions ;)

Thanks,
Alex

**Comment by dwhjames** [comment]
I would write that with a builder.

```scala
val builder = Map.newBuilder[String, AttributeValue]
builder += Attributes.accountId -> item.accountId
…
builder.result()
```

**Comment by alboko** [comment]
Dan,

Thanks, that's a better approach. What about fromAttributes:
	accountName = amap.get(Attributes.accountName).map(_.getS),
Is it a right way to go?

**Comment by dwhjames** [comment]
Yeah, I imagine I’ve done something like that previously.
