### ISSUE TITLE
Compile errors upgrading AWS to 1.10.5 and above - ambiguous reference in dynamodb

### ISSUE THREAD

**Issue by glidester** [dwhjames/aws-wrap#37]
I'm trying to incorporate the new CodeCommit API into the project but when I upgraded to the latest version of the AWS SDK I hit this issue (see compile errors at bottom of post).

I traced back to version 1.10.4.1 which is the latest version that still compiles ok. I had a look at the diff of these two versions but can't figure out what the breaking change is:

https://github.com/aws/aws-sdk-java/compare/1.10.4.1...1.10.5 

The only way I know how to fix this is to not use the 'wrapAsyncMethod' on these methods and just hand code the conversion of the java Future to a Scala one (not ideal).

This will need to be addressed so that we can move forward with the latest AWS developments and services.

Thanks.

`[error] /home/tim/v4/aws-wrap/src/main/scala/dynamodb/dynamodb.scala:45: ambiguous reference to overloaded definition,
[error] both method batchGetItemAsync in class AmazonDynamoDBAsyncClient of type (x$1: java.util.Map[String,com.amazonaws.services.dynamodbv2.model.KeysAndAttributes], x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.BatchGetItemRequest,com.amazonaws.services.dynamodbv2.model.BatchGetItemResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.BatchGetItemResult]
[error] and  method batchGetItemAsync in class AmazonDynamoDBAsyncClient of type (x$1: com.amazonaws.services.dynamodbv2.model.BatchGetItemRequest, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.BatchGetItemRequest,com.amazonaws.services.dynamodbv2.model.BatchGetItemResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.BatchGetItemResult]
[error] match expected type (?, com.amazonaws.handlers.AsyncHandler[?,?]) => java.util.concurrent.Future[?]
[error]     wrapAsyncMethod(client.batchGetItemAsync, batchGetItemRequest)
[error]                            ^
[error] /home/tim/v4/aws-wrap/src/main/scala/dynamodb/dynamodb.scala:64: ambiguous reference to overloaded definition,
[error] both method batchWriteItemAsync in class AmazonDynamoDBAsyncClient of type (x$1: java.util.Map[String,java.util.List[com.amazonaws.services.dynamodbv2.model.WriteRequest]], x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.BatchWriteItemRequest,com.amazonaws.services.dynamodbv2.model.BatchWriteItemResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.BatchWriteItemResult]
[error] and  method batchWriteItemAsync in class AmazonDynamoDBAsyncClient of type (x$1: com.amazonaws.services.dynamodbv2.model.BatchWriteItemRequest, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.BatchWriteItemRequest,com.amazonaws.services.dynamodbv2.model.BatchWriteItemResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.BatchWriteItemResult]
[error] match expected type (?, com.amazonaws.handlers.AsyncHandler[?,?]) => java.util.concurrent.Future[?]
[error]     wrapAsyncMethod(client.batchWriteItemAsync, batchWriteItemRequest)
[error]                            ^
[error] /home/tim/v4/aws-wrap/src/main/scala/dynamodb/dynamodb.scala:127: ambiguous reference to overloaded definition,
[error] both method deleteTableAsync in class AmazonDynamoDBAsyncClient of type (x$1: String, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.DeleteTableRequest,com.amazonaws.services.dynamodbv2.model.DeleteTableResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.DeleteTableResult]
[error] and  method deleteTableAsync in class AmazonDynamoDBAsyncClient of type (x$1: com.amazonaws.services.dynamodbv2.model.DeleteTableRequest, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.DeleteTableRequest,com.amazonaws.services.dynamodbv2.model.DeleteTableResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.DeleteTableResult]
[error] match expected type (?, com.amazonaws.handlers.AsyncHandler[?,?]) => java.util.concurrent.Future[?]
[error]     wrapAsyncMethod(client.deleteTableAsync, deleteTableRequest)
[error]                            ^
[error] /home/tim/v4/aws-wrap/src/main/scala/dynamodb/dynamodb.scala:143: ambiguous reference to overloaded definition,
[error] both method describeTableAsync in class AmazonDynamoDBAsyncClient of type (x$1: String, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.DescribeTableRequest,com.amazonaws.services.dynamodbv2.model.DescribeTableResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.DescribeTableResult]
[error] and  method describeTableAsync in class AmazonDynamoDBAsyncClient of type (x$1: com.amazonaws.services.dynamodbv2.model.DescribeTableRequest, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.DescribeTableRequest,com.amazonaws.services.dynamodbv2.model.DescribeTableResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.DescribeTableResult]
[error] match expected type (?, com.amazonaws.handlers.AsyncHandler[?,?]) => java.util.concurrent.Future[?]
[error]     wrapAsyncMethod(client.describeTableAsync, describeTableRequest)
[error]                            ^
[error] /home/tim/v4/aws-wrap/src/main/scala/dynamodb/dynamodb.scala:191: ambiguous reference to overloaded definition,
[error] both method listTablesAsync in class AmazonDynamoDBAsyncClient of type (x$1: Integer, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.ListTablesRequest,com.amazonaws.services.dynamodbv2.model.ListTablesResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.ListTablesResult]
[error] and  method listTablesAsync in class AmazonDynamoDBAsyncClient of type (x$1: String, x$2: com.amazonaws.handlers.AsyncHandler[com.amazonaws.services.dynamodbv2.model.ListTablesRequest,com.amazonaws.services.dynamodbv2.model.ListTablesResult])java.util.concurrent.Future[com.amazonaws.services.dynamodbv2.model.ListTablesResult]
[error] match expected type (?, com.amazonaws.handlers.AsyncHandler[?,?]) => java.util.concurrent.Future[?]
[error]     wrapAsyncMethod(client.listTablesAsync, listTablesRequest)`

**Comment by dwhjames** [comment]
It you take a look at the history for [AmazonDynamoDBAsync](https://github.com/aws/aws-sdk-java/commits/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBAsync.java)

You can see that it changed in `1.10.5` to add a bunch of overloads.

- `batchGetItemsAsync` [as of `1.9.33`](https://github.com/aws/aws-sdk-java/blob/6c2943a09b43d1ab1ca34da29b454847cf055bc0/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBAsync.java#L1573-L1575)
- `batchGetItemsAsync` [as of `1.10.5`](https://github.com/aws/aws-sdk-java/blob/a5349097a8c243e631c4b089e9c5d377d3d23787/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBAsync.java#L375-L417)

Hence the issue with the ambiguous overload.

I’ll take a look to see how this ambiguity can be resolved.

**Comment by dwhjames** [comment]
@glidester fixed in PR #38
