### ISSUE TITLE
Upgrading aws dependencies

### ISSUE THREAD

**Issue by Timshel** [dwhjames/aws-wrap#53]
Hello,

We are using `aws-wrap` as a dependency in [commons-aws](https://github.com/MfgLabs/commons-aws), do you intend to upgrade the aws dependencies ?

In the negative can we reuse the the code wrapping CloudWatch, S3 and SQS ?

Have a nice day.

**Comment by dwhitney** [comment]
+1 (I think you should submit a PR)

**Comment by Timshel** [comment]
There already is such a PR: https://github.com/dwhjames/aws-wrap/pull/50 in which the version can probably be bumped to `1.10.77`.

**Comment by mingchuno** [comment]
@Timshel @dwhitney 
I have forked this repo and published it under version 0.9.0
https://github.com/mingchuno/aws-wrap

Can you please check if you still have any problems? If yes, please submit an issue there
