### ISSUE TITLE
Examples needed!

### ISSUE THREAD

**Issue by tlockney** [dwhjames/aws-wrap#7]
I'm trying to wrap my head around how this library is intended to be used and keep running into features that appear to either be incomplete or that simply don't seem to do what I'd expect. But there's a fair chance I'm simply missing something obvious. Examples of usage would be most welcome, in particular for the DynamoDB wrappers.

**Comment by peoplemerge** [comment]
+1 more docs.

The src/it has ReadsOnHashKeyTableSpec, but would like to see some more query types.
